# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfbox < Formula
  desc "Another terraform version selector, combined with docker"
  homepage "https://github.com/vahid-haghighat/tfbox"
  version "1.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vahid-haghighat/tfbox/releases/download/v1.3.1/tfbox_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "e437fe08f0abdfc0cc117e68ad2a74664e4b95242a51c003dad1dc305adccd94"

      def install
        bin.install "tfbox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vahid-haghighat/tfbox/releases/download/v1.3.1/tfbox_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "0f4e43aa7fecc8e4be212ec72dfccda95adf68f7629333b2c8bc9641bec4f758"

      def install
        bin.install "tfbox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vahid-haghighat/tfbox/releases/download/v1.3.1/tfbox_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
        sha256 "67434efda8ae02d90924fdd749ab9ed7baabe1af5ac6e3d75ab036b719fb252a"

        def install
          bin.install "tfbox"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vahid-haghighat/tfbox/releases/download/v1.3.1/tfbox_Linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "b2b9fe042b9ef8899a96ebc9c8fa149ccc3b7e162d063a8f95356c607f83eacb"

        def install
          bin.install "tfbox"
        end
      end
    end
  end

  test do
    system "#{bin}/tfbox version"
  end
end
