# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfbox < Formula
  desc "Another terraform version selector, combined with docker"
  homepage "https://github.com/vahid-haghighat/tfbox"
  version "1.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vahid-haghighat/tfbox/releases/download/v1.3.2/tfbox_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "6d8fbc16d9402d302104d3e553fbf2eab7c27f15dc0e7e72516fc731c4cf8495"

      def install
        bin.install "tfbox"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vahid-haghighat/tfbox/releases/download/v1.3.2/tfbox_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "746b98358153d53ee3d5e4d4b6e018901cef6de5f6b17960066f3658e7df7f33"

      def install
        bin.install "tfbox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/vahid-haghighat/tfbox/releases/download/v1.3.2/tfbox_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "41b4c192cfebf3e1205fdebfb895ae348c72e7c54e8c6ebc9ef113732d7a2fc9"
      def install
        bin.install "tfbox"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/vahid-haghighat/tfbox/releases/download/v1.3.2/tfbox_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "0b3a6a011af800605b798d26596628f638e262b5ea4bd9f0e59cda1484d3e55e"
      def install
        bin.install "tfbox"
      end
    end
  end

  test do
    system "#{bin}/tfbox version"
  end
end
